# source: https://github.com/cvanoort/datalab_challenge_2/blob/master/source/sierra_leone.py
"""
References:
    - https://en.wikipedia.org/wiki/Subdivisions_of_Sierra_Leone
    - https://en.wikipedia.org/wiki/Districts_of_Sierra_Leone
    - https://en.wikipedia.org/wiki/Chiefdoms_of_Sierra_Leone
    - https://reliefweb.int/updates?source=1503&format=12.12570&advanced-search=(PC211)#content

Notes:
    - Two new districts, Falaba and Karene, were introduced in 2017.
        - https://en.wikipedia.org/wiki/Falaba_District
        - https://en.wikipedia.org/wiki/Karene_District
        - The number of Chiefdoms also increased from 149 to 190.
        - We are concerned with the structure from 2014-2015,
            so these new districts/chiefdoms are not included.

Issues:
    - How to handle Bo Town. It's not really a Chiefdom, but seems to be a separate entity?
        - Seems to be split into 3 Wards, each with several sections.
    - Similarly, Koidu Town in Kono.
"""

#
# Forward mappings (larger -> smaller)
#
province2districts = {
    'Eastern': ['Kailahun', 'Kenema', 'Kono'],
    'North West': ['Kambia', 'Port Loko'],
    'Northern': ['Bombali', 'Koinadugu', 'Tonkolili'],
    'Southern': ['Bo', 'Bonthe', 'Moyamba', 'Pujehun'],
    'Western': ['Western Rural', 'Western Urban'],
}

district2chiefdoms = {
    'Bo': [
        'Badjia',
        'Bagbo',
        'Bagbwe',
        'Baoma',
        'Bumpe Ngao',
        'Gbo',
        'Jaiama Bongor',
        'Kakua',
        'Komboya',
        'Lugbu',
        'Niawa Lenga',
        'Selenga',
        'Tikonko',
        'Valunia',
        'Wonde',
    ],
    'Bombali': [
        'Biriwa',
        'Bombali Shebora',
        'Gbanti Kamaranka',
        'Gbendembu Ngowahun',
        'Libeisaygahun',
        'Magbaimba Ndorh',
        'Makari Gbanti',
        'Paki Masabong',
        'Safroko Limba',
        'Sanda Loko',
        'Sanda Tendaran',
        'Sella Limba',
        'Tambakha',
    ],
    'Bonthe': [
        'Bendu-Cha',
        'Bonthe Urban',
        'Bum',
        'Dema',
        'Imperri',
        'Jong',
        'Kpanda Kemo',
        'Kwamebai Krim',
        'Nongoba Bullom',
        'Sittia',
        'Sogbeni',
        'Yawbeko',
    ],
    'Kailahun': [
        'Dea',
        'Jawei',
        'Kissi Kama',
        'Kissi Teng',
        'Kissi Tongi',
        'Kpeje Bongre',
        'Kpeje West',
        'Luawa',
        'Malema',
        'Mandu',
        'Njaluahun',
        'Penguia',
        'Upper Bambara',
        'Yawei',
    ],
    'Kambia': [
        'Bramaia',
        'Gbinle Dixing',
        'Magbema',
        'Mambolo',
        'Masungbala',
        'Samu',
        'Tonko Limba',
    ],
    'Kenema': [
        'Dama',
        'Dodo',
        'Gaura',
        'Gorama Mende',
        'Kandu Leppiama',
        'Koya (Kenema)',
        'Langrama',
        'Lower Bambara',
        'Malegohun',
        'Niawa',
        'Nomo',
        'Nongowa',
        'Simbaru',
        'Small Bo',
        'Tunkia',
        'Wandor',
    ],
    'Koinadugu': [
        'Dembelia Sinkunia',
        'Diang',
        'Folosaba Dembelia',
        'Kasunko',
        'Mongo',
        'Neya',
        'Nieni',
        'Sengbe',
        'Sulima',
        'Wara-Wara Bafodea',
        'Wara-Wara Yagala',
    ],
    'Kono': [
        'Fiama',
        'Gbane Kandor',
        'Gbane',
        'Gbense',
        'Gorama Kono',
        'Kamara',
        'Lei',
        'Mafindor',
        'Nimikoro',
        'Nimiyama',
        'Sandor',
        'Soa',
        'Tankoro',
        'Toli',
    ],
    'Moyamba': [
        'Bagruwa',
        'Bumpe',
        'Dasse',
        'Fakunya',
        'Kagboro',
        'Kaiyamba',
        'Kamajei',
        'Kongbora',
        'Kori',
        'Kowa',
        'Lower Banta',
        'Ribbi',
        'Timdale',
        'Upper Banta',
    ],
    'Port Loko': [
        'Bureh Kasseh',
        'Buya Romende',
        'Debia',
        'Kaffu Bullom',
        'Koya (Port Loko)',
        'Lokomasama',
        'Maforki',
        'Marampa',
        'Masimera',
        'Sanda Magbolontor',
        'T.M. Safroko',
    ],
    'Pujehun': [
        'Barri',
        'Gallines Perri',
        'Kpaka',
        'Kpanga Kabondeh',
        'Kpanga Krim',
        'Makpele',
        'Malen',
        'Mono Sakrim',
        'Peje',
        'Soro Gbema',
        'Sowa',
        'Yakemu Kpukumu Krim',
    ],
    'Tonkolili': [
        'Gbonkolenken',
        'Kafe Simiria',
        'Kalansogoia',
        'Kholifa Mabang',
        'Kholifa Rowalla',
        'Kunike Barina',
        'Kunike',
        'Malal Mara',
        'Sambaia',
        'Tane',
        'Yoni',
    ],
    'Western Rural': [
        'Koya Rural',
        'Mountain Rural',
        'Waterloo Rural',
        'York Rural',
    ],
    'Western Urban': [
        'Central 1',
        'Central 2',
        'East 1',
        'East 2',
        'East 3',
        'West 1',
        'West 2',
        'West 3',
    ],
}

chiefdom2sections = {
    'Badjia': [
        # Possibly one more section, missing name on map
        'Damai',
        'Kpallay',
        'Njargbahun',
        'Sei',
    ],
    'Bagbo': [
        'Bum',
        'Gorapon',
        'Jimmi',
        'Kpangbalia',
        'Mano',
        'Niagorehun',
        'Tissana',
    ],
    'Bagbwe': [
        # Possibly one more section, missing name on map
        'Jongo',
        'Niawa',
        'Nyallay',
        'Samawa',
    ],
    'Bagruwa': [
        'Benduma',
        'Benkeh',
        'Kawaya',
        'Kigbai',
        'Makassi',
        'Mani',
        'Moseilolo',
        'Palima',
        'Sembehun',
    ],
    'Baoma': [
        'Bambawo',
        'Fallay',
        'Kimaya',
        'Lower Pataloo',
        'Mawojeh',
        'Njeima',
        'Sonnah',
        'Upper Pataloo',
    ],
    'Barri': [
        'Dakona',
        'Fallay',
        'Jougba',
        'Karjei',
        'Laimba',
        'Malla',
        'Sonjour 1',
        'Sonjour 2',
        'Tetima',
    ],
    'Bendu-Cha': [
        'Gba-cha',
        'Sokenteh',
        'Tissagbe',
        'Yallan-gbokie',
    ],
    'Biriwa': [
        'Balandugu',
        'Bumban',
        'Bumbandain',
        'Kabakeh',
        'Kagbankuna',
        'Kamabai',
        'Karassa',
        'Karina',
        'Kayonkoro',
    ],
    'Bombali Shebora': [
        'Kafala',
        'Kagbaran Dokom',
        'Konta',
        'Matotoka',
    ],
    'Bonthe Urban': [
        'Bonthe Town',
    ],
    'Bramaia': [
        'Banguraia',
        'Bassia',
        'Bugami',
        'Duramania',
        'Filligungee',
        'Fortumboyie',
        'Gberekhuray',
        'Gbolon',
        'Kabaya',
        'Kanku Bramaia',
        'Konta',
        'Kua Bramaia',
        'Kufuru',
        'Kukuna',
        'Laminaia',
        'Sansangie',
        'Seduya',
        'Shekaia',
        'Sulaimania',
        'Teneba Bramaia',
        'Turaya',
    ],
    'Bum': [
        'Fikie',
        'Gbengain',
        'Gbondubum',
        'Koimato',
        'Lanje',
        'Tamba',
        'Torma',
        'Yargbe',
        'Yawma',
    ],
    'Bumpe': [
        'Bellentin',
        'Bumpeh',
        'Greema',
        'Kassipoto',
        'Mamu',
        'Massah',
        'Moforay',
        'Mokebbie',
        'Motobon',
        'Moyemi',
        'Saiama',
        'Samu',
        'Yengessa',
    ],
    'Bumpe Ngao': [
        'Bongo',
        'Bumpe',
        'Foya',
        'Kpetema',
        'Sahn',
        'Serabu',
        'Sewama',
        'Taninahun',
        'Walihun',
        'Yengema',
    ],
    'Bureh Kasseh': [
        'Barmoi',
        'Kagbanthama',
        'Kaiyeabor',
        'Kalangba',
        'Kambia Morie',
        'Konta Ferry',
        'Mabombo',
        'Makana',
        'Mamanka',
        'Mange Morie',
        'Marenka',
        'Minthormore',
        'Rogbla',
        'Romeni',
        'Rotifunk',
        'Yali-Sanda',
    ],
    'Buya Romende': [
        'Foredugu',
        'Gbaran Kamba',
        'Kamasundu',
        'Mabureh Buya',
        'Mabureh Mende',
        'Magbengbe',
        'Manungbu',
        'Petifu Bana',
        'Robis',
        'Rokel',
        'Rosint',
        'Worreh Mapoteh',
    ],
    'Central 1': [
        'Albert Academy',
        'Mountain Regent',
        'Sorie Town',
        "Susan's Bay",
    ],
    'Central 2': [
        'Connaught Hospital',
        'Sanders Brook',
    ],
    'Dasse': [
        'Bambuibu Tommy',
        'Bongoya',
        'Domboma',
        'Foya Tewei',
        'Jayahun',
        'Kenema',
        'Niti Korley',
        'Semabu',
        'Taninahun Gomoh',
        'Taninahun Kapuima',
        'Timindi',
        'Wonkifore',
    ],
    'Dea': [
        'Baiwalla',
        'Dodo',
        'Sakiema',
        'Sienga',
    ],
    'Debia': [
        'Karine',
        'Kayembor',
        'Konta Kargbo',
        'Mafonda',
        'Makabari',
        'Makump',
        'Rogbalan',
    ],
    'Dama': [
        'Dakowa',
        'Danyadejo',
        'Dassama',
        'Fowai',
        'Fowai',
        'Klajie',
        'Lower Dabor',
        'Upper Dabor',
    ],
    'Dema': [
        'Chepo',
        'Dema',
        'Turtle Islands',
        'Yoh',
    ],
    'Dembelia Sinkunia': [
        'Kunbulun 1',
        'Kunbulun 2',
        'Manan',
        'Mawundea',
        'Numula 1',
        'Numula 2',
        'Numula 3',
        'Numula 4',
        'Numula 5',
        'Sinkunia',
    ],
    'Diang': [
        'Darakuru',
        'Gbenekoro',
        'Kania',
        'Kondembaia',
        'Lengekoro',
        'Sokurala',
    ],
    'Dodo': [
        # Possibly two additional sections, missing names on map
        'Bambara',
        'Gorama',
        'Karteh',
        'Korgay',
        'Seiwor',
    ],
    'East 1': [
        'Cline Town',
        'Fourah Bay',
        'Kossoh Town',
    ],
    'East 2': [
        'Asho',
        'Bombay',
        'Coconut Farm',
        'Foulah Town',
        'Ginger Hall',
        'Kissy Brook',
        'Magazine',
        'Mount Aureol',
        'Quarry',
    ],
    'East 3': [
        'Allen Town 1',
        'Allen Town 2',
        'Bottom Oku',
        'Congo Water 1',
        'Congo Water 2',
        'Grass Field',
        'Industrial Estate',
        'Jalloh Terrace',
        'Kissy Brook',
        'Kissy Bye Pass 1',
        'Kissy Bye Pass 2',
        'Kissy Mental',
        'Kissy Mess Mess',
        'Kuntolor',
        'Lowcost Housing',
        'Mamba Ridge 1',
        'Mamba Ridge 2',
        'Mayenkineh',
        'Old Warf',
        'Pamuronko',
        'Portee',
        'Robis',
        'Rokupa',
        'Shell',
        'Thunderhill',
    ],
    'Fakunya': [
        'Central',
        'Fakoi',
        'Gandorhun',
        'Kovella',
        'Kpangulgo',
        'Kunyafoi',
        'Maninga',
        'Njawa',
        'Songo',
        'Tangbla',
        'To-Ndambalenga',
        'Tullu',
    ],
    'Fiama': [
        'Dumbia',
        'Fiama',
        'Kokar',
        'Kooma',
        'Yorkor',
    ],
    'Folosaba Dembelia': [
        'Balandugu',
        'Dogoloya',
        'Fissaya 1',
        'Fissaya 2',
        'Gbentu 3',
        'Herekor',
        'Kalia',
        'Kamba',
        'Lagor',
        'Musaia',
        'Sankan 1',
        'Sankan 2',
    ],
    'Gallines Perri': [
        'Bondor',
        'Dabeni',
        'Dakona',
        'Gendema 1',
        'Gendema 2',
        'Jakema 1',
        'Jakema 2',
        'Joya',
        'Kemokai',
        'Kortugbu',
        'Mallah',
        'Mewah',
        'Pelegbulor',
    ],
    'Gaura': [
        'Geibu',
        'Joru',
        'Kokoru',
        'Mendekelema',
        'Sandaru',
        'Sembehun',
    ],
    'Gbane': [
        'Gbane Yemao',
        'Gbinidakor',
        'Kamara',
        'Maikandor',
        'Mongo',
    ],
    'Gbane Kandor': [
        'Gbane Kandor',
        'Gbane Kour',
        'Gbane Tetema',
        'Gbendekor',
        'Yanbidu',
    ],
    'Gbanti Kamaranka': [
        'Gbenkfay',
        'Gbonkobana',
        'Kambia',
        'Kayourgbor',
        'Makulon',
        'Makumray A',
        'Makumray B',
        'Rogberay',
        'Romaneh',
        'Royeama A',
        'Royeama B',
        'Sakuma A',
        'Sakuma B',
        'Sendugu A',
        'Sendugu B',
    ],
    'Gbendembu Ngowahun': [
        'Garanganwa',
        'Gbendembu',
        'Kalangba',
        'Kania',
        'Lobanga',
        'Lohindie',
        'Loko-Madina',
        'Makai',
        'Makarihiteh',
        'Makeregbohun',
        'Makump',
        'Mamaka',
        'Mamukay',
        'Masongbo',
        'Matehun',
        'Mayorthan',
        'Sahun',
        'Tambiama',
        'Tanyehun',
    ],
    'Gbense': [
        'Banfinfeh',
        'Banyafeh',
        'Banyakor',
        'Moindefeh',
        'Moindekor',
    ],
    'Gbinle Dixing': [
        'Gbinle',
        'Kalangba',
        'Katalan',
        'Mafaray',
        'Maton',
        'Rogberay',
        'Sanda',
        'Tawuya',
    ],
    'Gbo': [
        'Gbo',
        'Maryu',
        'Nyawa',
    ],
    'Gbonkolenken': [
        'Lower Massakong',
        'Lower Polie',
        'Mayeppoh',
        'Petifu Mayawa A',
        'Petifu Mayawa B',
        'Petifu Mayeppoh',
        'Upper Massakong',
        'Upper Polie',
        'Yele Manowo',
        'Yiben',
    ],
    'Gorama Kono': [
        'Bunabu',
        'Kangama',
        'Selokoma',
    ],
    'Gorama Mende': [
        'Biatong',
        'Famanjo',
        'Kaklawa',
        'Kualley',
    ],
    'Imperri': [
        'Babum',
        'Bapus',
        'Bigo',
        'Kahekay',
        'Moimaligie',
        'Sokrapan',
    ],
    'Jaiama Bongor': [
        'Lower Baimba',
        'Lower Kama',
        'Lower Niawa',
        'Nekpondo',
        'Tongowa',
        'Upper Baimba',
        'Upper Kama',
        'Upper Niawa',
    ],
    'Jawei': [
        'Sowa',
        'Kaio',
        'Mano',
        'Bobor',
        'Upper Luyengeh',
        'Lower Luyengeh',
        'Upper Geibu',
        'Lower Geibu',
    ],
    'Jong': [
        'Basiaka',
        'Bayengbe',
        'Beyinga',
        'Falewuja',
        'Kumabeh-Kwe',
        'Landi Ngere',
        'Sopan-Cleveland',
        'Tucker-Nyambe',
    ],
    'Kafe Simiria': [
        'Kabaia',
        'Kamarugu',
        'Mabonto',
        'Makelfa',
        'Makontande',
        'Mayaso',
        'Simiria',
    ],
    'Kaffu Bullom': [
        'Foronkoya',
        'Kasongha',
        'Lungi',
        'Mahera',
        'Mamanki',
        'Mayaya',
        'Rosint',
        'Yongro',
    ],
    'Kagboro': [
        'Bendu A',
        'Bendu B',
        'Bumpetoke',
        'Konolor',
        'Mambo',
        'Mano',
        'Mobeh',
        'Mofuss',
        'Mokandor',
        'Mokebe',
        'Mokobo',
        'Mopaileh',
        'Moyah',
        'Moyibo',
        'Ngiehun',
        'Rembe',
        'Tassoh',
        'Thumba A',
        'Thumba B',
        'Yondu',
    ],
    'Kaiyamba': [
        'Angigboya',
        'Koromboya',
        'Kpange',
        'Lungili',
        'Mendegelema',
        'Mosoe',
        'Waliwahun',
    ],
    'Kakua': [
        # Possibly two more sections, missing names on map
        'Korjeh',
        'Kpandobu',
        'Nguabu',
        'Samamie',
        'Sewa',
        'Sindeh',
    ],
    'Kalansogoia': [
        'Fuladugu',
        'Kakallain',
        'Kamakathie',
        'Kamakilla',
        'Kasokira',
        'Lower Section',
        'Upper Section',
    ],
    'Kandu Leppiama': [
        'Borley',
        'Gboro-Lokoma',
        'Karga',
        'Sonnie',
    ],
    'Kamajei': [
        'Kowama',
        'Mogbuama',
        'Ngiegombu',
        'Ngoahun',
        'Njagbema',
        'Tawovehun',
        'Yeima',
    ],
    'Kamara': [
        'Gbondu',
        'Kongofinja',
        'Sukudu',
    ],
    'Kasunko': [
        'Gbonkobor',
        'Kakallain',
        'Kasunko',
        'Kayaka',
        'Tamiso 1',
        'Tamiso 2',
    ],
    'Kholifa Mabang': [
        'Kumrabai',
        'Mabang',
        'Marunia Koray',
        'Marunia Sakie',
    ],
    'Kholifa Rowalla': [
        'Bo Road',
        'Lal Lenken',
        'Mamuntha',
        'Mayatha',
        'Mayossoh',
        'Old Maguraka',
    ],
    'Kissi Kama': [
        'Dakaleley',
        'Kama Teng',
        'Kama Toh',
    ],
    'Kissi Teng': [
        'Bumasadu',
        'Kundu',
        'Lela',
        'Torli',
    ],
    'Kissi Tongi': [
        'Bende Bengu',
        'Konio',
        'Pokorli',
        'Tongi Tingi',
    ],
    'Komboya': [
        # Possibly two more sections, missing names on map
        'Mangaru',
        'Keisua',
        'Kemoh',
    ],
    'Kongbora': [
        'Gibina',
        'Gondama',
        'Mobondor',
        'Mokorewo',
        'Mongere',
        'Mosongla',
        'Mowoto',
        'Senehun',
        'Taninihun',
        'Tongieh',
    ],
    'Kori': [
        'Zone 1',
        'Zone 2',
        'Zone 3',
        'Zone 4',
        'Zone 5',
        'Zone 6',
        'Zone 7',
    ],
    'Kowa': [
        # Possibly one more section, name missing on map
        'Kpandobu',
        'Mosumana',
        'Ngiyeiya',
        'Njama',
        'Tabe',
        'Tawoveihun',
    ],
    'Koya (Kenema)': [
        'Joi',
        'Koya Gbundohun',
        'Menima',
        'Serabu',
        'Upper Koya',
    ],
    'Koya (Port Loko)': [
        'Benkia',
        'Fondu',
        'Foredugu',
        'Futa',
        'Gbabai',
        'Kagbala A',
        'Kagbala B',
        'Magbandoma',
        'Magbeni',
        'Mahera',
        'Marefa',
        'Matene',
        'Mathirie',
        'Mawoma',
        'Robia',
        'Rokel',
        'Roponka',
        'Rosarr',
        'Sanda',
        'Tumba',
    ],
    'Koya Rural': [
        'Fabaina Area',
        'Madonkeh',
        'Magbafti',
        'Malambay',
        'Netwon',
        'Songo',
    ],
    'Kpaka': [
        'Jassende Kpeima',
        'Jassende Masaoma',
        'Jassende Ngoleima',
        'Nyango-Ngoleihun',
        'Nyango-Njeigbla',
        'Parvu',
        'Sarbah',
    ],
    'Kpanda Kemo': [
        'Ba-Kobotu',
        'Bewoni',
        'Gbonge',
        'Senjehun',
        'Sewama',
        'Taokunor',
    ],
    'Kpanga Krim': [
        'Fassei',
        'Somasa',
    ],
    'Kpanga Kabondeh': [
        'Bakoi',
        'Banyande',
        'Kabonde',
        'Kondogbe',
        'Panga',
        'Pessekeh',
        'Samba',
        'Setti-Yakanday',
        'Upper Kayiemba',
    ],
    'Kpeje Bongre': [
        'Bongre',
        'Borkou',
        'Falloh',
        'Jorwu',
        'Manowa',
        'Marwei',
        'Seimaya',
    ],
    'Kpeje West': [
        'Bunumbu',
        'Golama',
        'Kpaewa',
        'Kpindima',
    ],
    'Kunike': [
        'Masingbi',
        'Rolal',
        'Sanda',
        'Semorkanie',
        'Thamah',
        'Thambaya',
        'Wana',
        'Yenkeh',
    ],
    'Kunike Barina': [
        'Mamurie',
        'Makali',
        'Mathonkara',
        'Wonkibor',
        'Masaba',
        'Makong',
    ],
    'Kwamebai Krim': [
        'Kpanga Koimato',
        'Kwako Lanten',
        'Massa Settie',
        'Mosenten Sahen 2',
        'Tubla',
        'Tun-Tun Sullay',
        'Yikie Karbay',
    ],
    'Langrama': [
        'Korjei',
        'Njeiwoma',
    ],
    'Lei': [
        'Dia',
        'Kensay',
        'Koaro',
        'Lei',
        'Sangbada',
        'Tankoro',
        'Tingi-Kor',
        'Yawai',
    ],
    'Libeisaygahun': [
        'Batkanu',
        'Mafonda',
        'Magbaingba',
        'Magbanamba',
        'Makaiba',
        'Makayrembay',
        'Mandawahun',
        'Manyakoi',
        'Mayankay',
        'Robaka',
        'Rotha-Tha',
        'Simbaya',
    ],
    'Lokomasama': [
        'Benkia',
        'Gbainty',
        'Kamasondo',
        'Kantaya',
        'Katonga',
        'Komrabi',
        'Konta',
        'Magbokorr',
        'Mannah',
        'Mapiterr',
        'Matheng',
        'Petifu',
        'Royema',
        'Yurika',
    ],
    'Lower Bambara': [
        'Bonya',
        'Fallay',
        'Gboro',
        'Korjei Buima',
        'Korjei Ngieya',
        'Nyawa',
        'Sei',
    ],
    'Lower Banta': [
        'Bengelloh',
        'Gbangbatoke',
        'Largoh',
        'Mofindoh',
        'Mokotawa',
        'Ndendemoya',
        'Ngolala',
        'Njagbahun',
        'Wulbange',
    ],
    'Luawa': [
        'Gao',
        'Gbela',
        'Giehun',
        'Lower Kpombali',
        'Luawa Foguiya',
        'Mano-Sewallu',
        'Mende Buima',
        'Mofindor',
        'Upper Kpombali',
    ],
    'Lugbu': [
        # Possibly one more section, missing name on map
        'Gao',
        'Kamba',
        'Kargbevu',
        'Magbao',
        'Yorma',
    ],
    'Mafindor': [
        'Kamiendor',
        'Kutey',
        'Mafindor',
    ],
    'Maforki': [
        'Batpolon',
        'Fenka',
        'Gberray Bana',
        'Gberray Morie',
        'Gberray Thunkara',
        'Gbonko Mayira',
        'Kabata',
        'Komrabi Waterloo',
        'Maboni',
        'Maforay',
        'Magbankitha',
        'Magbengbeh',
        'Magbeni',
        'Makorobolai',
        'Malal',
        'Mamanso',
        'Mapolie',
        'Maronko',
        'Marunia',
        'Massebay',
        'Mathera',
        'Moria',
        'Old Port Loko',
        'Romaka',
        'Rosarr',
        'Sendugu',
        'Tauya',
    ],
    'Magbema': [
        'Bombe',
        'Kamba',
        'Kambia',
        'Kargbulor',
        'Robat',
        'Rokupr',
        'Tormina',
    ],
    'Magbaimba Ndorh': [
        'Hunduwa',
        'Kababala',
        'Kagberay',
        'Kawungulu',
        'Makendema',
        'Mambiama',
        'Manjahagha',
        'Sokudala',
        'Yana',
    ],
    'Makari Gbanti': [
        'Gborbana',
        'Mabanta',
        'Magbenteh',
        'Mangay',
        'Mankene',
        'Masongbo A',
        'Masongbo B',
        'Punthun',
        'Rosint',
        'Tonkoba',
        'Yainkassa',
    ],
    'Makpele': [
        'Kengo',
        'Samagbe',
        'Seitua',
        'Selimeh',
    ],
    'Malal Mara': [
        'Kiamp Kakolo',
        'Mabilafu',
        'Makoba',
        'Malal',
        'Manewa',
        'Mara',
        'Matanka',
        'Rochen',
    ],
    'Malegohun': [
        'Hulorhun Njagbudor',
        'Hulorhun Njeigor',
        'Konjo Buiima',
        'Konjo Njeigor',
        'Konjo Yematanga',
        'Lower Torgboma',
        'Upper Torgboma',
    ],
    'Malema': [
        'Bamburu',
        'Lower Sami',
        'Njagbla',
        'Pelegbambeima',
        'Upper Sami',
    ],
    'Malen': [
        'Bahoin',
        'Kahaimoh',
        'Kakpanda',
        'Kemoh',
        'Korwa',
        'Lower Pemba',
        'Seijeila',
        'Taukunor',
        'Upper Pemba',
    ],
    'Mambolo': [
        'Kalenkay',
        'Mambolo'
        'Matetie',
        'Mayakie',
        'Robis',
        'Rowollon',
        'Tombo-Wallah',
    ],
    'Mandu': [
        'Gbongre',
        'Levuma Jeibla',
        'Lower Kuiva',
        'Upper Kuiva',
    ],
    'Mono Sakrim': [
        'Gbomoti',
        'Kemoh',
        'Makpondo',
        'Masanda Majagbe',
        'Pembaar',
        'Pullie',
        'Sitta',
        'Sowa',
    ],
    'Marampa': [
        'Magbele',
        'Mange',
        'Marampa',
        'Mawullay',
        'Mines',
        'Path Bana',
        'Petifu Madina',
        'Rogballan',
        'Rolankonoh',
    ],
    'Masimera': [
        'Biki',
        'Biss-Manika',
        'Katick',
        'Maconteh',
        'Mamalikie',
        'Masimera',
        'Matuku',
        'Mayola-Thatha',
        'Nonkoba',
        'Rokel',
        'Rokon/Komboya',
        'Yoni-Pet',
    ],
    'Masungbala': [
        'Bamoi',
        'Benna',
        'Kawula',
        'Kayenkassa',
        'Mapolon',
        'Maserie',
        'Matengha',
        'Matilba',
        'Nonko',
        'Samu',
        'Sumbuya',
        'Thalla',
    ],
    'Mongo': [
        'Benadugu',
        'Deldugu',
        'Mankalia',
        'Mofgindugu',
        'Mongo 1',
        'Mongo 2',
    ],
    'Mountain Rural': [
        'Bathurst',
        'Charlotte',
        'Gloucester',
        'Leicester',
        'Regent',
    ],
    'Neya': [
        'Kulor',
        'Neya 1',
        'Neya 2',
        'Nyedu',
        'Saradu',
    ],
    'Niawa': [
        'Bandawor',
        'Kpatawa',
        'Mabondor',
        'Niawa',
        'Vaama',
    ],
    'Niawa Lenga': [
        # Possibly two more sections, missing names on map
        'Baimba',
        'Yalenga',
    ],
    'Nieni': [
        'Barawa',
        'Kalian',
        'Sumbaria',
        'Wollay',
        'Yiffin',
    ],
    'Nimikoro': [
        # Possibly one more section, name missing on map
        'Bandafafeh',
        'Gbogboafeh',
        'Jaiama',
        'Masayiefeh',
    ],
    'Nimiyama': [
        # Possibly one more section, name missing on map
        'Njagbakahun',
        'Njaifeh',
        'Peyifeh',
        'Tama',
    ],
    'Njaluahun': [
        'Bombowa',
        'Dan Sei',
        'Falley',
        'Fauya',
        'Gboo',
        'Jonga',
        'Kargbu',
        'Keimaya',
        'Lower Nyawa',
        'Sei 1',
        'Sei 2',
        'Upper Nyawa',
    ],
    'Nomo': [
        'Faama',
        'Ngeibu',
        'Ngiewoma-Njeigor',
    ],
    'Nongoba Bullom': [
        'Baoma',
        'Bohol',
        'Bullom',
        'Garinga',
        'Gbangbassa',
        'Gbap',
        'Hahun',
        'Kessie',
        'Manyime',
        'Pelewahun',
        'Salma',
        'Solon',
        'Torma Subu',
    ],
    'Nongowa': [
        'Dagbanya',
        'Dakpana',
        'Gbo Kakajama B',
        'Gbo Lambayama B',
        'Kagbado Kamboima',
        'Kagbado Njeigbla',
        'Kona Foiya',
        'Kona Kpindibu',
    ],
    'Paki Masabong': [
        'Kathanthan',
        'Kathegeya',
        'Mapaki',
        'Masabong',
        'Mayagba',
        'Rosanda',
    ],
    'Peje': [
        'Koilenga',
        'Peje East',
        'Peje West',
    ],
    'Penguia': [
        'Bulima',
        'Jagor',
        'Kumatandu',
        'Lombama',
        'Nimima',
    ],
    'Ribbi': [
        'Kentineh',
        'Lower Ribbi',
        'Makera',
        'Masanka',
        'Masarakulay',
        'Mobureh',
        'Motoni',
        'Motonkoh',
        'Upper Ribbi',
        'Yoni',
    ],
    'Safroko Limba': [
        'Binkolo 1',
        'Binkolo 2',
        'Bombali Bana',
        'Kabonka',
        'Kasengbeh',
        'Kayassi',
        'Mabamba',
        'Masapi',
    ],
    'Sambaia': [
        'Borowah',
        'Buyan',
        'Dayie',
        'Sambaia',
    ],
    'Samu': [
        'Bubuya',
        'Kassiri',
        'Koya',
        'Kychom',
        'Lusenia',
        'Mafufuneh',
        'Makuma',
        'Mange',
        'Mapotolon',
        'Moribaia',
        'Rokon',
        'Rosinor',
    ],
    'Sanda Loko': [
        'Banka',
        'Benia',
        'Kaindema',
        'Kamalu',
        'Kindia',
        'Laminaya',
        'Madina',
        'Maharibo',
        'Makapa',
        'Makwie Loko',
        'Manathi',
        'Maparay',
        'Rothatha',
        'Timbo',
    ],
    'Sanda Tendaran': [
        'Kukuna',
        'Marampa',
        'Masisan',
        'Mateboi',
        'Rogbin',
        'Rogboreh',
        'Rosos',
        'Sendugu',
        'Yankabala',
    ],
    'Sanda Magbolontor': [
        'Bankro',
        'Gbaneh-Loko',
        'Gbogbodo',
        'Gbonko',
        'Kantia',
        'Layamantmetank',
        'Magbolontor',
        'Malkiya',
        'Mankneh',
        'Masien',
        'Robis',
        'Rotigbonko',
        'Sendugu',
    ],
    'Sandor': [
        'Bafinfeh',
        'Dangbaidu',
        'Kawafeh',
        'Njeikor',
        'Samgbafeh',
        'Sinkongofeh',
        'Sumunjifeh',
        'Tharma Forest',
        'Yawatanda',
    ],
    'Selenga': [
        'Kaduawo',
        'Mokpendeh',
        'Old Town',
    ],
    'Sella Limba': [
        'Samia',
        'Kayimbor',
        'Kamakwie',
        'Magbonkoni 1',
        'Manonkoh',
        'Magbonkoni 2',
        'Kamankoh',
    ],
    'Sengbe': [
        'Bendugu',
        'Heremakono',
        'Koinadugu',
        'Lower Kamadugu',
        'Upper Kamadugu',
        'Yogomaia',
    ],
    'Simbaru': [
        'Bundoryama',
        'Yalenga',
    ],
    'Sittia': [
        'Bamba',
        'Gonoh',
        'Kamai',
        'Kwalloh',
        'Moh',
        'Saama',
        'Sahaya',
        'Sahn-Gbengu',
        'Sampoh',
        'Yoni',
    ],
    'Small Bo': [
        # Possibly three more sections, names missing on map
        'Kamboma',
        'Sowa',
    ],
    'Soa': [
        'Foidu Mongor',
        'Kokongokuma',
        'Maindu',
        'Mofinkor',
        'Sawa Buma',
        'Sawa Fiama',
        'Tensekor',
        'Tensendakor',
    ],
    'Sogbeni': [
        'Bakumba',
        'Beyorgboh',
        'Ndopie',
        'Pengor',
    ],
    'Soro Gbema': [
        'Kemokai',
        'Kengo',
        'Kiazombo',
        'Mano River',
        'Massaquoi 1',
        'Massaquoi 2',
        'Moiwebu',
        'Zoker 1',
        'Zoker 2',
        'Zombo',
    ],
    'Sowa': [
        'Lower Geoma',
        'Sabba 1',
        'Sabba 2',
        'Upper Geoma',
    ],
    'Sulima': [
        'Biribaia',
        'Dara',
        'Falaba',
        'Fudea',
        'Ganya',
        'Gberia Fotombu',
        'Gberia-Timbako',
        'Kaliyereh',
        'Kambaia',
        'Laylay',
        'Nomokoya',
        'Sonkoya',
    ],
    'T.M. Safroko': [
        'Gbaray Bana',
        'Kambia',
        'Kanu',
        'Kargbo',
        'Konkorie',
        'Mafonikay',
        'Magbafth',
        'Magbapasa',
        'Malakuray',
        'Maron',
        'Robombeh',
    ],
    'Tambakha': [
        'Dugutha',
        'Moria',
        'Paramount Chief Se',
        'Simibue',
        'Thalla',
    ],
    'Tane': [
        'Maboboh Koray',
        'Makrugbeh',
        'Mange-bana',
        'Mapakie',
        'Mathunkara',
        'Matotoka',
    ],
    'Tankoro': [
        # Possibly one more section, name missing on map
        'Njama',
        'Woafeh',
    ],
    'Tikonko': [
        'Bainyawa',
        'Mambawa',
        'Morku',
        'Ngolamajie',
        'Njagbla 1',
        'Njagbla 2',
        'Seiwa',
        'Sendeh',
    ],
    'Timdale': [
        'Bembellor',
        'Gambia',
        'Gbehan',
        'Kamasunu',
        'Kambotoke',
        'Kebail',
        'Mandu',
        'Mye',
        'Nonkoba',
        'Sahan',
        'Tombeh',
        'Yapoma',
    ],
    'Toli': [
        'Bawadu',
        'Komadu',
        'Kwidu',
    ],
    'Tonko Limba': [
        'Bubuya',
        'Kamassassa',
        'Kathanthineh',
        'Magbonkoh',
        'Mamankoh',
        'Yebaya',
    ],
    'Tunkia': [
        'Daru',
        'Gegbwema',
        'Giewoma',
        'Gorahun',
        'Jewahun',
        'Kuawuma',
        'Taninahun',
    ],
    'Upper Bambara': [
        'Bambara',
        'Bomaru-guma',
        'Goleiwoma',
        'Golu',
        'Korbu',
        'Naiahun',
    ],
    'Upper Banta': [
        'Bei-Kelleh',
        'Kenafallay',
        'Kepay',
        'Mogongbe',
        'Songbo',
    ],
    'Valunia': [
        'Deilenga',
        'Kendebu',
        'Lunia',
        'Ngovo',
        'Seilenga',
        'Vanjelu',
        'Yarlenga',
    ],
    'Wara-Wara Bafodea': [
        'Taelia',
        'Kambalia',
        'Kambia',
        'Pampakoh',
        'Bafodia',
        'Kamayortortor',
        'Kamanikie',
        'Kakoya',
        'Semamaia',
        'Kaponpon',
        'Kadanso',
    ],
    'Wara-Wara Yagala': [
        'Zone 1',
        'Zone 2',
        'Zone 3',
        'Zone 4',
        'Zone 5',
        'Zone 6',
        'Zone 7',
    ],
    'Waterloo Rural': [
        'Benguema Village',
        'Campbell Town Village',
        'Hastings Village',
        'Waterloo Village',
    ],
    'West 1': [
        'Ascension Town',
        'Brookfields',
        'Kingtom',
        'Kroo Town',
    ],
    'West 2': [
        'Brookfields-Congo',
        'Brookfields-Red Pu',
        'Congo Town',
        'George Brook',
        'New England-Hannes',
        'New England-Hill',
        'Tengbeh Town',
    ],
    'West 3': [
        'Aberdeen',
        'Cockerill-Aberdeen',
        'Cockle-Bay',
        'Hill Station',
        'Juba/Kaningo',
        'Lumley',
        'Malama/Kamayama',
        'Murray Town',
        'Pipeline/Wilkinson',
        'Wilberforce',
    ],
    'Wonde': [
        'Central Kargoi',
        'Lower Kargoi',
        'Manye',
        'Upper Kargoi',
    ],
    'Wandor': [
        # May be one more section, name missing on map
        'Boryongor',
        'Gbogbeima',
        'Kemoh',
        'Songhai',
        'Tongorwa',
    ],
    'Yakemu Kpukumu Krim': [
        'Bagollay',
        'Bapawa',
        'Bekowa',
        'Fortune',
        'Kemo-Bo',
        'Kemo-wa',
        'Kpukumu',
        'Seiwoh',
        'Sowonde',
        'Yabai',
    ],
    'Yawbeko': [
        # Possibly one more section, name missing on map
        'Baryegbe',
        'Ketaway',
        'Mobulie',
        'Yorma',
    ],
    'Yawei': [
        'Kuiva Jagor',
        'Kuivawa',
        'Bendu',
        'Kuiva Buima',
    ],
    'Yoni': [
        'Foindu',
        'Gaindema',
        'Lower Petifu',
        'Macrogba',
        'Makeni Rokefula',
        'Malanchor',
        'Malompor',
        'Masengbe',
        'Mayira',
        'Ronietta',
        'Upper Petifu',
        'Yoni',
    ],
    'York Rural': [
        'Gbendembu',
        'Goderich-Adonkia',
        'Goderich-Funkia',
        'Hamilton',
        'Kent',
        'Sattia',
        'Tombo',
        'York',
    ],
}

#
# Reverse mappings (smaller -> larger)
#
district2province = {
    district: province
    for province, districts in province2districts.items()
    for district in districts
}
chiefdom2district = {
    chiefdom: district
    for district, chiefdoms in district2chiefdoms.items()
    for chiefdom in chiefdoms
}
section2chiefdom = {
    section: chiefdom
    for chiefdom, sections in chiefdom2sections.items()
    for section in sections
}

#
# Lists
#
provinces = sorted(province2districts.keys())
districts = sorted(district2chiefdoms.keys())
chiefdoms = sorted(chiefdom2sections.keys())
sections = sorted([y for x in chiefdom2sections.values() for y in x])


#
# Tests to ensure agreement between the different mappings and lists
#
def test_districts():
    districts_p = sorted([district for districts in province2districts.values() for district in districts])
    assert districts == districts_p


def test_chiefdoms():
    chiefdoms_d = sorted([chiefdom for chiefdoms in district2chiefdoms.values() for chiefdom in chiefdoms])
    assert chiefdoms == chiefdoms_d


def test_sections():
    sections_c = sorted([section for sections in chiefdom2sections.values() for section in sections])
    assert sections == sections_c
